binarytree : binarytree.c binarytree.test.c
	gcc -g binarytree.c binarytree.test.c

redblack : redblacktree.c redblacktree.test.c
	gcc -g redblacktree.c redblacktree.test.c

debug : a.out
	gdb a.out

clean : a.out
	rm a.out
